### ISSUE TITLE
flash cancels on my systems

### ISSUE THREAD

**Issue by WiredLife** [RFStorm/mousejack#12]
on ubuntu 14.04 lts and kali 2016 i got the same errors

root@kali:~/mousejack# make install
./prog/usb-flasher/usb-flash.py bin/dongle.bin
[2016-03-19 20:12:32.832]  Looking for a compatible device that can jump to the Nordic bootloader
[2016-03-19 20:12:32.897]  Device found, jumping to the Nordic bootloader
Traceback (most recent call last):
  File "./prog/usb-flasher/usb-flash.py", line 70, in <module>
    else: dongle.ctrl_transfer(0x40, 0xFF, 0, 0, (), timeout=usb_timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
Makefile:25: die Regel für Ziel „install“ scheiterte
make: **\* [install] Fehler 1

tried
sudo pip install -U -I pip && sudo pip install -U -I pyusb
with no success

please help me

**Comment by atechdad** [comment]
I don't know if this helps, but I had to update to the lastest stock firmware before I could flash the research firmware...
I started here: https://github.com/bitcraze/crazyradio-firmware

**Comment by WiredLife** [comment]
That was it, thanks!
