### ISSUE TITLE
Tools doesnt work

### ISSUE THREAD

**Issue by realdaveger** [RFStorm/mousejack#13]
Hi there, 

first i have successfully flashed the firmware of the CrazyRadio PA USB dongle. After flashing, it is always the red led on?! And lsusb gives ID 1915:0102 Nordic Semiconductor ASA

all the tools i called gives me no feedback and after several minutes i cancelled the action and it gives me this output:

> CTraceback (most recent call last):
>   File "./nrf24-scanner.py", line 55, in <module>
>     value = common.radio.receive_payload()
>   File "/home/hand/Downloads/MouseJack - Cracyfly/mousejack-master/tools/lib/nrf24.py", line 91, in receive_payload
>     self.send_usb_command(RECEIVE_PAYLOAD, ())
>   File "/home/hand/Downloads/MouseJack - Cracyfly/mousejack-master/tools/lib/nrf24.py", line 120, in send_usb_command
>     self.dongle.write(0x01, data, timeout=nrf24.usb_timeout)
>   File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 948, in write
>     self.__get_timeout(timeout)
>   File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 824, in bulk_write
>     timeout)
>   File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 917, in __write
>     timeout)
> KeyboardInterrupt

im using: 
pyusb==1.0.0rc1
libusb-1.0-0

anyone known this issue?

Thanks

**Comment by realdaveger** [comment]
pyusb reinstalled und its working now, next time i should use the verbose output earlier.

this case is closed
