### ISSUE TITLE
Not detecting Logitech Unifying Receiver after make logitech_install

### ISSUE THREAD

**Issue by gracelee** [RFStorm/mousejack#32]
Hi I have been working on this mousejack with my logitech unifying receiver U0007.
I did 'sudo make logitech_install', and this gave me the following error:

[2017-05-08 13:13:44.271]  20:00:01:0F:00:6B:32:FF:FF:FF:FF:FF:FF:FF:32:FF:FF:FF:FF:FF:EF:DC:75:B6:40:11:D0:00:C7:C7:9D:1F
[2017-05-08 13:13:44.271]  Mark firmware update as completed
[2017-05-08 13:13:44.654]  20:00:00:01:02:6B:32:FF:FF:FF:FF:FF:FF:FF:32:FF:FF:FF:FF:FF:EF:DC:75:B6:40:11:D0:00:C7:C7:9D:1F
[2017-05-08 13:13:44.655]  Restarting dongle into research firmware mode
Traceback (most recent call last):
  File "./prog/usb-flasher/logitech-usb-flash.py", line 65, in <module>
    response = dongle.send_command(0x21, 0x09, 0x0200, 0x0000, "\x70" + "\x00"*31)
  File "/home/grace/mousejack/nrf-research-firmware/prog/usb-flasher/unifying.py", line 180, in send_command
    response = self.dongle.read(ep, 32, timeout=timeout)
  File "/home/grace/.local/lib/python2.7/site-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/home/grace/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 851, in intr_read
    timeout)
  File "/home/grace/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/home/grace/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
Makefile:33: recipe for target 'logitech_install' failed
make: *** [logitech_install] Error 1

Then all of sudden, my logitech mouse stop working and it is disconnected. So I checked whether the dongle is recongized by my ubuntu with 'lsusb', but it seems like it is not recongized well.

Does anybody know why this happened and how I fix this issue? 

Thank you all

**Comment by dxflatline** [comment]
Same here. It does not start in "research firmware mode".

Nevertheless I managed to return the firmware using the **prog/usb-flasher/logitech-usb-restore.py XXXXX.hex**

I opened the http://chilp.it/3465237 using ResEdit and extracted a file looking like:
:0A00000002038A0080FD05264A2253
:07000B0080FE75B5FF8025A2
:0700130080FE80200217ECC3

Renamed it to .hex and restored it successfully.
lsusb shows it as Logitech, Inc. Unified Receiver again.

If anyone knows why the problem appears, please let us know.
